### ISSUE TITLE
/startsmoke only produces small sparks

### ISSUE THREAD

**Issue by rhys19** [Albo1125/FireScript#2]
so i used /startsmoke 5.0 and it only produces small sparks any idea? i'd like to start smoke to some rp with a house full of smoke.

**Comment by Albo1125** [comment]
@rhys19 thanks, will look into this

**Comment by Albo1125** [comment]
@rhys19 please try the latest release, should be fixed, please let me know on here.
Will close if no feedback within 3 days.

**Comment by rhys19** [comment]
ok i will try it out thanks!

**Comment by Albo1125** [comment]
Fixed!
