### ISSUE TITLE
Fire Goes out too Fast

### ISSUE THREAD

**Issue by YesItsLew** [Albo1125/FireScript#4]
When using a fire extinguisher  it takes about a second for the fire to be put out.

Example: https://gyazo.com/efd2122fff61dd065419a6c6379fbb4d

**Comment by Albo1125** [comment]
Should be fixed in the latest release 1.4.0

If no further reply will close.

**Comment by YesItsLew** [comment]
Tried to put new version in my server and now fires don't spawn

**Comment by Albo1125** [comment]
Try restarting your server. Please give full reproduction steps. Working perfectly fine on my server.

**Comment by YesItsLew** [comment]
Not sure if it should be like this?
![image](https://user-images.githubusercontent.com/43212955/56432762-8e2ef700-62c6-11e9-83a1-ac3d3a3dd3e1.png)
Because the older version looks like this:
![image](https://user-images.githubusercontent.com/43212955/56432779-a6067b00-62c6-11e9-9994-151eee8d2984.png)

**Comment by Albo1125** [comment]
Replace the files in the latest release with the new ones. You have cloned the repo.. https://github.com/Albo1125/FireScript/releases/tag/v1.4.0
